apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        version: ${VERSION}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${IMAGE}
          envFrom:
            - configMapRef:
                name: ${SERVICE_NAME}
                optional: true
            - configMapRef:
                name: ${SERVICE_NAME}-terraform
                optional: true
            - secretRef:
                name: ${SERVICE_NAME}
                optional: true
            - secretRef:
                name: ${SERVICE_NAME}-terraform
                optional: true
          ports:
            - name: tcp
              containerPort: 9080
