apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
    service: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: ${SERVICE_NAME}
