name: Github Actions CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ details, productpage, ratings, reviews ]
        include:
          - service: reviews
            skip_image: true
    steps:
      ###
      # prepare
      ###
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ###
      # docker image
      ###
      - name: Extract metadata (tags, labels) for details
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.actor }}/${{ matrix.service }}
          tags: |
            type=sha
      - if: ${{ !matrix.skip_image }}
        name: Build and push Docker image
        id: docker_push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./apps/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Output docker tags
        id: docker_tag
        run: echo "${{ matrix.service }}=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT
    outputs:
      details: ${{ steps.docker_tag.outputs.details }}
      productpage: ${{ steps.docker_tag.outputs.productpage }}
      ratings: ${{ steps.docker_tag.outputs.ratings }}
      reviews: ${{ steps.docker_tag.outputs.reviews }}

  generate-manifest:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      ###
      # prepare
      ###
      - name: Checkout the repository
        uses: actions/checkout@v3

      ###
      # kustomize
      ###
      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2
      - run: |
          service=(
            'details'
            'productpage'
            'ratings'
            'reviews'
          )
          images=(
            '${{ needs.build-and-push-image.outputs.details }}'
            '${{ needs.build-and-push-image.outputs.productpage }}'
            '${{ needs.build-and-push-image.outputs.ratings }}'
            '${{ needs.build-and-push-image.outputs.reviews }}'
          )
          platform=('minikube' 'colima')
          env=('dev')
          
          for ((idx=0; idx<${#service[@]}; ++idx)); do
            s=${service[idx]}
            i=${images[idx]}
          
            for p in "${platform[@]}"; do
              for e in "${env[@]}"; do
                echo "$s" "$p" "$e" "$i"
                ./scripts/kustomize_build_ci.sh "$s" "$p" "$e" "$i"
              done
            done
          done

      ###
      # git commit
      ###
      - name: Auto push the manifest
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: github-actions
          message: "auto generated manifest"
